#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6463419564                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/picai-ai-art-generator/id6463419564?l=tr                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Unlock art with AI! Using Stable Diffusion XL, turn text into stunning visuals. Dive into the future of creativity with PicAI.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Talha Yavçın                               
your_link                                 : https://bento.me/talhayavcin                     
your_city                                 : Istanbul                                
email_address                             : talhayavcin23@gmail.com
facebook_username                         :                                           
instagram_username                        : talhayavcin
twitter_username                          : talhayavcin
github_username                           : talhayavcin
youtube_username                          :
mastodon_link                             : 



features:

  - title                                 : Welcome to PicAI
    description                           : Your personal AI-powered art generator. Enter a prompt, and watch as PicAI crafts beautiful artwork right before your eyes.
    fontawesome_icon_name                 : paint-brush
    
  - title                                 : Transform Your Photos
    description                           : Upload a photo, choose a creative prompt, and let PicAI turn it into a piece of art. Rediscover your memories in a new artistic light.
    fontawesome_icon_name                 : image
    
  - title                                 : Artistic Prompts
    description                           : Explore a vast array of creative prompts designed to ignite your imagination and add a unique artistic touch to your photos.
    fontawesome_icon_name                 : lightbulb
    
  - title                                 : Intuitive Interface
    description                           : With PicAI's user-friendly interface, diving into the world of digital art has never been easier or more fun.
    fontawesome_icon_name                 : magic
    
  - title                                 : Fast and Powerful
    description                           : Experience lightning-fast art generation thanks to our optimized AI algorithms. Your artwork is ready in seconds.
    fontawesome_icon_name                 : bolt
    
  - title                                 : Community and Support
    description                           : Join our growing community of creative minds and find inspiration for your next project. Our team is here to provide support whenever you need.
    fontawesome_icon_name                 : users

  - title                                 : Easy Sharing
    description                           : Share your creations effortlessly on social media platforms or with our community.
    fontawesome_icon_name                 : share-alt
    
  - title                                 : Regular Updates
    description                           : Enjoy regular updates bringing new features, prompts, and enhancements to the PicAI experience.
    fontawesome_icon_name                 : sync
    
  - title                                 : In-App Tutorials
    description                           : Easy-to-follow tutorials to get you started and uncover the full potential of PicAI.
    fontawesome_icon_name                 : question-circle



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
